//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDD.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAS_User()
        {
            this.UDPSet = new HashSet<UDPSet>();
            this.BAS_UR = new HashSet<BAS_UR>();
        }
    
        public System.Guid Id { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Con_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UDPSet> UDPSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAS_UR> BAS_UR { get; set; }
        public virtual BAS_UserLogin BAS_UserLogin { get; set; }
    }
}
