//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDD.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_OOSet
    {
        public System.Guid Id { get; set; }
    
        public virtual BAS_Object BAS_Object { get; set; }
        public virtual BAS_ObjectSet BAS_ObjectSet { get; set; }
    }
}
