//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDD.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_PermissionAssign
    {
        public System.Guid Id { get; set; }
    
        public virtual BAS_PermissionContainer BAS_PermissionContainer { get; set; }
        public virtual BAS_IdentityContainer BAS_IdentityContainer { get; set; }
        public virtual BAS_ObjectContainer BAS_ObjectContainer { get; set; }
    }
}
