//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDD.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_UDPSet
    {
        public System.Guid Id { get; set; }
        public bool IsMain { get; set; }
    
        public virtual BAS_User BAS_User { get; set; }
        public virtual BAS_Post BAS_Post { get; set; }
        public virtual BAS_Department BAS_Department { get; set; }
    }
}
