//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDD.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public System.Guid Id { get; set; }
        public int Amount { get; set; }
        public decimal LineTotal { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual ProductInfo ProductInfo { get; set; }
    }
}
