//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDD.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalesOrdersModelContainer : DbContext
    {
    
        public virtual DbSet<BAS_PermissionContainer> BAS_PermissionContainer { get; set; }
        public virtual DbSet<BAS_IdentityContainer> BAS_IdentityContainer { get; set; }
        public virtual DbSet<BAS_ObjectContainer> BAS_ObjectContainer { get; set; }
        public virtual DbSet<BAS_PermissionAssign> BAS_PermissionAssign { get; set; }
        public virtual DbSet<BAS_Object> BAS_Object { get; set; }
        public virtual DbSet<BAS_ObjectSet> BAS_ObjectSet { get; set; }
        public virtual DbSet<BAS_OOSet> BAS_OOSet { get; set; }
        public virtual DbSet<BAS_Permission> BAS_Permission { get; set; }
        public virtual DbSet<BAS_PermissionSet> BAS_PermissionSet { get; set; }
        public virtual DbSet<BAS_PPSet> BAS_PPSet { get; set; }
        public virtual DbSet<BAS_User> BAS_User { get; set; }
        public virtual DbSet<BAS_Post> BAS_Post { get; set; }
        public virtual DbSet<BAS_Department> BAS_Department { get; set; }
        public virtual DbSet<BAS_UDPSet> BAS_UDPSet { get; set; }
        public virtual DbSet<BAS_Role> BAS_Role { get; set; }
        public virtual DbSet<BAS_PR> BAS_PR { get; set; }
        public virtual DbSet<BAS_UR> BAS_UR { get; set; }
        public virtual DbSet<BAS_DR> BAS_DR { get; set; }
        public virtual DbSet<BAS_UserLogin> BAS_UserLogin { get; set; }
    }
}
